title: Bryan's Blog
theme: minima
author: Bryan Lynch
email: bml312@nyu.edu
exclude:
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
defaults:
  - scope:
      path: ""
    values:
      css: "/assets/css/custom.css"
